use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Display dimensions — must match `bootloader::oled::{WIDTH, HEIGHT}`.
const WIDTH: usize = 128;
const HEIGHT: usize = 64;
const FRAME_SIZE: usize = WIDTH * (HEIGHT / 8);

fn main() {
    // Put `memory.x` in our output directory and ensure it's on the linker search path.
    let out = env::var("OUT_DIR").unwrap();
    let out_dir = Path::new(&out);
    fs::copy("memory.x", out_dir.join("memory.x")).unwrap();
    println!("cargo:rustc-link-search={out}");
    println!("cargo:rerun-if-changed=memory.x");

    // `--nmagic` is required if memory section addresses are not aligned to 0x10000,
    // for example the FLASH and RAM sections in your `memory.x`.
    // See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
    println!("cargo:rustc-link-arg=--nmagic");

    println!("cargo:rustc-link-arg=-Tlink.x");

    build_images(out_dir);
}

/// Compile every 128x64 PNG in `images/` into a `FrameBuffer` static.
///
/// The generated file (always emitted, even when the directory is empty or
/// missing) is included by `src/images.rs`.
fn build_images(out_dir: &Path) {
    // Once any rerun-if-changed is emitted, cargo no longer auto-watches build.rs.
    println!("cargo:rerun-if-changed=build.rs");
    let images_dir = Path::new("images");
    // Rerun whenever the directory changes (added/removed/modified files).
    println!("cargo:rerun-if-changed=images");

    let mut generated = String::from(
        "// AUTO-GENERATED by build.rs. Do not edit.\n\
         use crate::oled::FrameBuffer;\n\n",
    );

    if images_dir.exists() {
        let mut pngs: Vec<PathBuf> = fs::read_dir(images_dir)
            .expect("read images/")
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x.eq_ignore_ascii_case("png")))
            .collect();
        // Deterministic order across platforms.
        pngs.sort();

        for path in &pngs {
            println!("cargo:rerun-if-changed={}", path.display());
            let bytes = png_to_framebuffer(path);
            let name = file_stem_to_ident(path);
            emit_static(&mut generated, &name, &bytes, path);
        }
    }

    fs::write(out_dir.join("images.rs"), generated).expect("write images.rs");
}

/// Convert `foo-bar.png` -> `FOO_BAR`. Panics on names that can't form a valid
/// SCREAMING_SNAKE_CASE Rust identifier.
fn file_stem_to_ident(path: &Path) -> String {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_else(|| panic!("image filename is not valid UTF-8: {}", path.display()));

    let mut name = String::with_capacity(stem.len());
    for c in stem.chars() {
        if c.is_ascii_alphanumeric() {
            name.push(c.to_ascii_uppercase());
        } else {
            name.push('_');
        }
    }
    assert!(
        !name.is_empty() && !name.starts_with(|c: char| c.is_ascii_digit()),
        "image filename {stem:?} cannot form a Rust identifier"
    );
    name
}

/// Decode a 128x64 PNG into the SSD1312 page-major 1bpp layout used by
/// `oled::FrameBuffer`.
///
/// Pixel is "on" iff (luma * alpha / 255) >= 128, with luma computed via the
/// ITU-R BT.601 weights. Transparent regions count as off.
fn png_to_framebuffer(path: &Path) -> [u8; FRAME_SIZE] {
    let file = fs::File::open(path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let mut decoder = png::Decoder::new(file);

    // Normalise weird formats to one of: Gray8 / GrayAlpha8 / Rgb8 / Rgba8.
    // EXPAND: expand 1/2/4-bit, palette → RGB, tRNS → alpha.
    // STRIP_16: drop the low byte of 16-bit channels.
    decoder.set_transformations(png::Transformations::EXPAND | png::Transformations::STRIP_16);

    let mut reader = decoder
        .read_info()
        .unwrap_or_else(|e| panic!("read header of {}: {e}", path.display()));
    let info = reader.info();
    assert!(
        info.width as usize == WIDTH && info.height as usize == HEIGHT,
        "{}: expected {}x{}, got {}x{}",
        path.display(),
        WIDTH,
        HEIGHT,
        info.width,
        info.height
    );

    let mut buf = vec![0u8; reader.output_buffer_size()];
    let frame = reader
        .next_frame(&mut buf)
        .unwrap_or_else(|e| panic!("decode {}: {e}", path.display()));
    let raw = &buf[..frame.buffer_size()];

    // Decide the number of bytes per pixel after transformation.
    let bpp: usize = match frame.color_type {
        png::ColorType::Grayscale => 1,
        png::ColorType::GrayscaleAlpha => 2,
        png::ColorType::Rgb => 3,
        png::ColorType::Rgba => 4,
        other => panic!(
            "{}: unexpected post-transform colour type {:?}",
            path.display(),
            other
        ),
    };
    assert!(
        frame.bit_depth == png::BitDepth::Eight,
        "{}: expected 8-bit channels after transform, got {:?}",
        path.display(),
        frame.bit_depth
    );

    let row_bytes = WIDTH * bpp;
    let mut out = [0u8; FRAME_SIZE];

    for y in 0..HEIGHT {
        let row = &raw[y * row_bytes..y * row_bytes + row_bytes];
        for x in 0..WIDTH {
            let p = &row[x * bpp..x * bpp + bpp];
            let (luma, alpha) = match frame.color_type {
                png::ColorType::Grayscale => (p[0] as u16, 255u16),
                png::ColorType::GrayscaleAlpha => (p[0] as u16, p[1] as u16),
                png::ColorType::Rgb => (luma_bt601(p[0], p[1], p[2]), 255),
                png::ColorType::Rgba => (luma_bt601(p[0], p[1], p[2]), p[3] as u16),
                _ => unreachable!(),
            };
            // Premultiply alpha against a black background, then threshold.
            let on = (luma * alpha / 255) >= 128;
            if on {
                let idx = (y / 8) * WIDTH + x;
                out[idx] |= 1u8 << (y % 8);
            }
        }
    }
    out
}

fn luma_bt601(r: u8, g: u8, b: u8) -> u16 {
    // u32 intermediate: 299 * 255 = 76245 overflows u16 (max 65535).
    ((299 * r as u32 + 587 * g as u32 + 114 * b as u32) / 1000) as u16
}

fn emit_static(out: &mut String, name: &str, bytes: &[u8; FRAME_SIZE], path: &Path) {
    let file_name = path.file_name().and_then(|n| n.to_str()).unwrap_or("?");
    writeln!(out, "/// Framebuffer compiled from `images/{file_name}`.").unwrap();
    writeln!(out, "pub static {name}: FrameBuffer = FrameBuffer([").unwrap();
    for chunk in bytes.chunks(16) {
        out.push_str("    ");
        for b in chunk {
            write!(out, "0x{b:02X},").unwrap();
        }
        out.push('\n');
    }
    out.push_str("]);\n\n");
}
